# Generated by Django 3.2.24 on 2024-10-18 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_auto_20241018_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 14, 25, 1, 592535)),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=469270, max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 10, 19, 14, 25, 1, 593273))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
