# Generated by Django 3.2.24 on 2024-11-27 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_auto_20241018_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 18, 29, 10, 159831)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=489785, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 18, 29, 10, 160650)),
        ),
    ]
