from django.utils.translation import gettext as _


maximum_doctors = "maximum_doctors"
invalid_credentials = "invalid_credentials"
invalid_id = "invalid_id"
denied = "denied"
success = "success"
maximum_patients = "maximum_patients"
invalid_request = "invalid_request"
maximum_visits = "maximum_visits"
speciality_not_found = "speciality_not_found"
used_username = "used_username"
wrong_password = "wrong_password"
used_number = "used_number"
start_conflict = "start_conflict"
end_conflict = "end_conflict"
not_doctor = "not_doctor"
expired_account = "expired_account"
not_found = "not_found"
