# Generated by Django 3.2.24 on 2024-08-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0002_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
